<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\external\ffxiv_navmesh\DotRecast\src\DotRecast.Core\DotRecast.Core.csproj" />
    <ProjectReference Include="..\..\external\ffxiv_navmesh\DotRecast\src\DotRecast.Detour\DotRecast.Detour.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\zone_names.json" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

</Project>
